language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libboost1.55-all-dev
    - cmake
    - lcov
    - doxygen
    - graphviz

install:
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov


before_script:
  - mkdir build
  - cd build
  - cmake ..
  - lcov --directory . --zerocounters

script:
  - make
  - ctest

after_success:
  #run initial
  - lcov --capture --initial --directory . --output-file cover
  #run tests
  - make test
  #run final
  - lcov --no-checksum --directory . --capture --output-file cover.info 
  #remove external dependencies
  - lcov --remove cover.info 'usr/*' --output-file cover.info 
  #remove test dependencies
  - lcov --remove cover.info '*test*' --output-file cover.info 
  - lcov --list cover.info # debug before upload
  - coveralls-lcov cover.info # uploads to coveralls

